openapi: 3.0.0

info:
  title: ByteBank Api
  version: 1.0.0
  description: Administra a movimentação bancária do correntista e controla o acesso através de CPF e senha.
  
  termsOfService: http://localhost:8085/bytebank-api/v1/termo-uso
  contact:
    name: Suporte
    url: http://localhost:8085/bytebank-api/v1/suporte
    email: suporte@bytebankapi.com

servers:
  - url: localhost:8085/bytebank-api/v1
    description: Main (production) server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      
  schemas:
    Cliente:              
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 234
        titular:
          type: string
          example: Janete Silva
        cpf:
          type: string
          maxLength: 11
          minLength: 11
          example: 22211100099
        senha:
          type: string
          format: password
          example: senha123
        conta:
          type: array
          items: 
            $ref: '#/components/schemas/Conta'
    
    Conta:
      type: object
      properties:
        agencia:
          type: integer
          format: int32
          example: 1234
        numero:
          type: integer
          format: int64
          example: 22222
        digito:
          type: integer
          format: int32
          example: 4
        saldo:
          type: number
          format: double
          example: 101.34
        cliente:
          $ref: '#/components/schemas/Cliente'
        transacoes:
          type: array
          items:
            $ref: '#/components/schemas/Transacao'
    
    Transacao:
      type: object
      properties:
        id: 
          type: integer
          format: int64
        tipo:
          type: string
          enum:
            - debito
            - deposito
        valor:
          type: number
          format: double
        data:
          type: string
          format: date-time
        conta:
          $ref: '#/components/schemas/Conta'
    
    Extrato:
      type: object
      properties:
        transacoes:
          type: array
          items:
            $ref: '#/components/schemas/Transacao'

security:
  - BasicAuth: []


tags: 
  - name: Cliente
  - name: Conta
  - name: Extrato
  - name: Transacao 

paths:
  /cliente:
    post:
      tags:
       - Cliente
      summary: Cadastra Cliente
      description: Cadastra um novo cliente
      operationId: cadastraCliente
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        '201':
          description: Cadastro efetuado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '400': 
          description: Requisição inválida
        '500':
          description: Erro interno no servidor
          
          
  /conta/{agencia}/{numero}/{digito}/saldo: 
    get:
      tags:
       - Conta
      summary: Consulta Saldo 
      description: Consulta o saldo da conta do cliente.
      operationId: consultaSaldo
      parameters: 
        - in: path
          name: agencia
          schema:
            type: integer
            format: int32
          required: true
        - in: path
          name: numero
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: digito
          schema:
            type: integer
            format: int32
          required: true
      responses:
        '200':
          description: Consulta a saldo efetuada com sucesso.
          content:
            application/json:
              schema:
                type: number
                format: double
        '400':
          description: Requisição inválida
        '401':
          description: Requisição não autorizada
        '500':
          description: Erro interno no servidor
    
  /transacao:
    post:
      tags:
        - Transacao
      summary: Cadastra transação na conta
      description: Cadastra uma transação de débito ou depósito na conta.
      operationId: cadastraTransacao
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Transacao'
        required: true
      parameters:
        - in: query
          name: tipo
          schema:
            type: string
            enum: 
              - debito
              - deposito
          required: true
      responses:
        '201':
          description: Cadastro de transação efetuado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transacao'
        '400':
          description: Requisição inválida
        '401':
          description: Requisição não autorizada
        '500':
          description: Erro no servidor    
  
  /extrato/{agencia}/{numero}/{digito}:
    get:
      tags:
       - Extrato
      summary: Consulta Extrato 
      description: Consulta o extrato da conta do cliente.
      operationId: consultaExtrato
      security: 
        - BasicAuth: []
      parameters: 
        - in: path
          name: agencia
          schema:
            type: integer
            format: int32
          required: true
        - in: path
          name: numero
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: digito
          schema:
            type: integer
            format: int32
          required: true
      responses:
        '200':
          description: Consulta a extrato efetuada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Extrato'
        '400':
          description: Requisição inválida
        '401':
          description: Requisição não autorizada
        '500':
          description: Erro interno no servidor
  
  /transacao/{codigo}:
    put:
      tags:
       - Transacao
      summary: Altera o valor da Transação
      description: Altera o valor da transação existente na conta do cliente
      security:
        - BasicAuth: []
      operationId: alteraValorTransacao
      parameters:
        - in: path
          name: codigo
          schema:
            type: integer
            format: int64
          required: true
        - in: query
          name: valor
          schema:
            type: number
            format: double
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Alteração do valor efetuada com sucesso
        '400':
          description: Requisição inválida
        '401':
          description: Requisição não autorizada
        '500':
          description: Erro interno no servidor
          
    delete:
      tags:
       - Transacao
      summary: Exclui a Transação
      description: Exclusão da transação existente na conta do cliente
      operationId: excluiTransacao
      parameters:
        - in: path
          name: codigo
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '204':
          description: Transação excluída com sucesso
        '400':
          description: Requisição inválida
        '401':
          description: Requisição não autorizada
        '500':
          description: Erro interno no servidor